---

- name: logstash-configure | Disable logstash-web
  service: name=logstash-web state=stopped enabled=no
  when: not logstash_web_enabled
  tags: [logstash, logstash-configure]

- name: logstash-configure | Enable logstash-web
  service: name=logstash-web state=started enabled=yes
  when: logstash_web_enabled
  tags: [logstash, logstash-configure]

- name: logstash-configure | Setup configuration files
  template:
    dest: "{{logstash_confdir}}/conf.d/{{item}}"
    group: "{{logstash_group}}"
    owner: "{{logstash_user}}"
    src: etc/logstash/conf.d/{{item}}.j2
    validate: "{{logstash_home}}/bin/logstash --configtest --config %s"
  notify: [logstash restart]
  with_items: [ 10-inputs.conf, 30-filters.conf, 50-outputs.conf ]
  tags: [logstash, logstash-configure]

- name: logstash-configure | Ensure the service is started
  service: name=logstash state=started enabled=yes
  changed_when: False
  tags: [logstash, logstash-configure]
