---

- name: logstash-install | Add Elasticsearch apt key.
  apt_key: url={{logstash_apt_key}}

- name: logstash-install | Add repository
  apt_repository: repo='{{logstash_apt_repo}}' update_cache=yes

- name: logstash-install | Install Logstash.
  apt: name=logstash

- name: logstash-install | Add Logstash user to adm group (Debian).
  user: name=logstash group=logstash groups=adm
  when: ansible_os_family == "Debian"
  notify: logstash restart
