---

- name: logstash-install | Add repositories
  apt_repository: repo='{{item}}' update_cache=yes
  with_items: logstash_apt_repositories

- name: logstash-install | Accept Oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
         creates=/usr/lib/jvm/java-7-oracle

- name: logstash-install | Install commmon packages
  apt: pkg={{item}}
  with_items: logstash_apt_common_pkgs

- name: logstash-install | Download logstash
  get_url: url={{logstash_url}} dest={{logstash_home}}/logstash.deb
  register: logstash_downloaded
  when: logstash_server_enabled or logstash_web_enabled

- name: logstash-install | Install logstash
  apt: deb={{logstash_home}}/logstash.deb
  when: logstash_downloaded.changed

- name: logstash-install | Download logstash forwarder
  get_url: url={{logstash_forwarder_url}} dest={{logstash_home}}/logstash-forwarder.deb
  register: logstash_forwarder_downloaded
  when: logstash_forwarder_enabled

- name: logstash-install | Install logstash forwarder
  apt: deb={{logstash_home}}/logstash-forwarder.deb
  when: logstash_forwarder_downloaded.changed
