---

- include: install.deb.yml
  when: ansible_os_family == 'Debian'
  tags: [logstash, logstash-install]

- include: configure.yml
  tags: [logstash, logstash-configure]

- include: plugins.yml
  tags: [logstash, logstash-plugins]
